### ISSUE TITLE
can I re-use the constants you wrote for the registers?

### ISSUE THREAD

**Issue by flynneva** [RoboticArts/ros_imu_bno055#3]
hi @RoboticArts!  im working on updating the [ROS2 bno055 package](https://github.com/flynneva/bno055) ive been working on and was wondering if I can just go ahead and "copy and paste" the registers you have written down.  the documentation and choice of variable names i really like looking at them, and since these are constants that have to do with the hardware...it would really help me out and save me a bunch of time if I could just copy and paste them over.

what do you think?

**Comment by RoboticArts** [comment]
Hi @flynneva 

I'm glad this repository helps you. Feel free to import what you need from the code :) Regarding the documentation I would ask you to add a link to this repository or a mention.

**Comment by flynneva** [comment]
awesome stuff @RoboticArts, thanks! ill close this then and keep you posted on my updates when I eventually find some time to get to it 😄
